### PR TITLE
chore(docs): update license file and license header to Apache 2.0

### PR DESCRIPTION
**Pull request by dtfiedler**
PE-6762

### CODE REVIEW

**Review by thiagocarvalhodev — APPROVED** [review]

**Comment by fedellen** [comment]
I still see mention of AGPL in contributing: 
image

**Comment by dtfiedler** [comment]
> 246c873

[246c873](https://github.com/ardriveapp/turbo-sdk/pull/179/commits/246c87323be48e977e55a7b5464bfd1ab107f144)

**Comment by dtfiedler** [comment]
> I still see mention of AGPL in contributing: image

[246c873](https://github.com/ardriveapp/turbo-sdk/pull/179/commits/246c87323be48e977e55a7b5464bfd1ab107f144)

**Review by fedellen — APPROVED** [review]

**Pull request merged**
